version: '3.9'

networks:
  domjudge:
    name: domjudge

services:
  mariadb:
    container_name: mariadb
    image: mariadb:latest
    networks:
      - domjudge
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=rootpw
      - MYSQL_USER=domjudge
      - MYSQL_PASSWORD=djpw
      - MYSQL_DATABASE=domjudge
    command: --max-connections=1000

  domserver:
    container_name: domserver
    image: domjudge/domserver:latest
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    networks:
        domjudge:
                aliases:
                        - smupc.online
    ports:
      - 80:80
    hostname: smupc.online
    depends_on:
      - mariadb
    environment:
      - CONTAINER_TIMEZONE=Asia/Seoul
      - MYSQL_HOST=mariadb
      - MYSQL_ROOT_PASSWORD=rootpw
      - MYSQL_USER=domjudge
      - MYSQL_PASSWORD=djpw
      - MYSQL_DATABASE=domjudge

  judgehost-0:
    container_name: judgehost-0
    image: domjudge/judgehost:latest
    privileged: true
    hostname: judgedaemon-0
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    networks:
      - domjudge
    depends_on:
      - domserver
    environment:
      - CONTAINER_TIMEZONE=Asia/Seoul
      - JUDGEDAEMON_USERNAME=judgehost
      - DAEMON_ID=0
      - JUDGEDAEMON_PASSWORD=3tt8+YHUWqsv76P5dcF3yU/oCnHNkt2J

  judgehost-1:
    container_name: judgehost-1
    image: domjudge/judgehost:latest
    privileged: true
    hostname: judgedaemon-1
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    networks:
      - domjudge
    depends_on:
      - domserver
    environment:
      - CONTAINER_TIMEZONE=Asia/Seoul
      - DAEMON_ID=1
      - JUDGEDAEMON_USERNAME=judgehost-2
      - JUDGEDAEMON_PASSWORD=smupcjudge1906

  judgehost-2:
    container_name: judgehost-2
    image: domjudge/judgehost:latest
    privileged: true
    hostname: judgedaemon-2
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    networks:
      - domjudge
    depends_on:
      - domserver
    environment:
      - CONTAINER_TIMEZONE=Asia/Seoul
      - JUDGEDAEMON_USERNAME=judgehost-3
      - DAEMON_ID=0
      - JUDGEDAEMON_PASSWORD=smupcjudge1906

  judgehost-3:
    container_name: judgehost-3
    image: domjudge/judgehost:latest
    privileged: true
    hostname: judgedaemon-3
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    networks:
      - domjudge
    depends_on:
      - domserver
    environment:
      - CONTAINER_TIMEZONE=Asia/Seoul
      - JUDGEDAEMON_USERNAME=judgehost-4
      - DAEMON_ID=0
      - JUDGEDAEMON_PASSWORD=smupcjudge1906
